import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author A.Narvel
 *
 */
public final class RSSReader {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSReader() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        // initialize to empty if no children
        String title = "Empty Title";
        String description = "No description";

        // get title element and assign title to the label
        int titleIndex = getChildElement(channel, "title");
        if (titleIndex != -1 && channel.child(titleIndex).numberOfChildren() > 0) {
            title = channel.child(titleIndex).child(0).label();
        }

        // get description element and assign description to the label
        int descripIndex = getChildElement(channel, "description");
        if (descripIndex != -1 && channel.child(descripIndex).numberOfChildren() > 0) {
            description = channel.child(descripIndex).child(0).label();
        }

        // get link element and assign link to the label
        int linkIndex = getChildElement(channel, "link");
        String link = "";
        if (linkIndex != -1 && channel.child(linkIndex).numberOfChildren() > 0) {
            link = channel.child(linkIndex).child(0).label();
        }

        // opening tags in HTML
        out.println("<html>");
        out.println("<head>");
        out.println("<title>" + title + "</title>"); // page title
        out.println("</head>");
        out.println("<body>");
        out.println("<h1><a href=\"" + link + "\">" + title + "</a></h1>");
        out.println("<p>" + description + "</p>"); // page description
        // create table with the date source and news
        out.println("<table border=\"1\">");
        out.println("<tr><th>Date</th><th>Source</th><th>News</th></tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        // close the table and HTML
        out.println("</table>");
        out.println("</body>");
        out.println("</html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        //initialize index to -1
        int index = -1;
        // iterate through XMLTree to find and return the index of the tag
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            if (xml.child(i).label().equals(tag) && index == -1) {
                index = i;
            }
        }
        return index; // return index or -1 if not found
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        //initialize to none available if no children
        String pubDate = "No date available";
        String source = "No source available";
        String titleOrDescrip = "No title available";
        String link = "";

        // get elements and assign variable to label

        int pubDateIndex = getChildElement(item, "pubDate");
        if (pubDateIndex != -1 && item.child(pubDateIndex).numberOfChildren() > 0) {
            pubDate = item.child(pubDateIndex).child(0).label();
        }

        int sourceIndex = getChildElement(item, "source");
        if (sourceIndex != -1 && item.child(sourceIndex).numberOfChildren() > 0) {
            String url = item.child(sourceIndex).attributeValue("url");
            source = item.child(sourceIndex).child(0).label();
            source = "<a href=\"" + url + "\">" + source + "</a>";

        }

        int titleIndex = getChildElement(item, "title");
        int descripIndex = getChildElement(item, "description");

        if (titleIndex != -1 && item.child(titleIndex).numberOfChildren() > 0) {
            titleOrDescrip = item.child(titleIndex).child(0).label();
        } else if (descripIndex != -1
                && item.child(descripIndex).numberOfChildren() > 0) {
            titleOrDescrip = item.child(descripIndex).child(0).label();
        }

        int linkIndex = getChildElement(item, "link");
        if (linkIndex != -1 && item.child(linkIndex).numberOfChildren() > 0) {
            link = item.child(linkIndex).child(0).label();
            titleOrDescrip = "<a href=\"" + link + "\">" + titleOrDescrip + "</a>";
        }

        // outputs row with pubDate source and title or description
        out.println("<tr>");
        out.println("<td>" + pubDate + "</td>");
        out.println("<td>" + source + "</td>");
        out.println("<td>" + titleOrDescrip + "</td>");
        out.println("</tr>");

    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        // ask user for URL and name of an output file
        out.println("Enter the URL of the RSS 2.0 feed: ");
        String url = in.nextLine();

        out.println("Enter the name of an output file (including the .html extension)");
        String outputFile = in.nextLine();
        SimpleWriter fileOut = new SimpleWriter1L(outputFile);

        //create XMLTree
        XMLTree rss = new XMLTree1(url);

        // if statement to make sure url is a valid rss feed
        if (rss.label().equals("rss") && rss.hasAttribute("version")
                && rss.attributeValue("version").equals("2.0")) {

            XMLTree channel = rss.child(0);

            outputHeader(channel, fileOut); //output html header

            // iterate through each child to find and process each item
            for (int i = 0; i < channel.numberOfChildren(); i++) {
                if (channel.child(i).label().equals("item")) {
                    processItem(channel.child(i), fileOut);
                }

            }

            outputFooter(fileOut); // output html footer
        } else {
            out.println("Invalid RSS 2.0 feed.");
        }

        in.close();
        out.close();
    }

}
